In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('023083_Maxi.csv')

In [3]:
df

,TIMESTAMP,Actuation Status,Alarm contact,Alarm contact text,Autorestart,Autorestart text,CMS air pressure,CMS elapsed time,Campo scala analizzatore ossigeno base,Cloud Status,...,Transfer pressure,Transfer time,Tron,Tron_col1,Tron_col2,Type of generator not set,Utilization,Utilization month,ip address,status simple
0,2023-09-29T21:53:46.226Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-09-29T21:53:45.704Z,NaN,1.0,Ox alarm,1.0,Automatic,NaN,NaN,1.0,NaN,...,NaN,NaN,79.0,NaN,NaN,0.0,8.0,15.0,NaN,189.0
2,2023-09-29T21:50:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-09-29T21:44:44.752Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-09-29T21:44:38.850Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
349550,2023-07-31T22:00:42.889Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349551,2023-07-31T22:00:41.868Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349552,2023-07-31T22:00:41.465Z,NaN,1.0,Ox alarm,1.0,Automatic,NaN,NaN,1.0,NaN,...,NaN,NaN,0.0,NaN,NaN,0.0,0.0,0.0,NaN,189.0
349553,2023-07-31T22:00:40.727Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
349554,2023-07-31T22:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10228069.0,8723350.0,NaN,NaN,NaN,NaN,NaN